repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: local
  hooks:
    - id: format-python
      name: Python - autoflake, isort, black
      entry: bash -c 'make format'
      language: system
      types: [python]
      pass_filenames: false
